# Test 2024-01-09 at 03:38:00

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Install Flask
      run: |
        sudo pip3 install flask

    - name: Run Flask
      run: |
        timeout 1m flask run & (
          sleep 2;
          curl -s http://127.0.0.1:5000;
          curl -s http://127.0.0.1:5000/goodBye
        )
